### ISSUE TITLE
Charts Referencing and Folder Hierarchy

### ISSUE THREAD

**Issue by MarkAshraf96** [eclipse-tractusx/item-relationship-service#126]
Hello,
I watched the system demo in PI8, and I wanted to ask about the subcharts folder directory, and why was this hierarchy chosen and not the common one to just put the dependencies in the charts folder where you can reference them by name?
Also why not use the released charts for those products instead of maintaining them at the repository?

**Comment by MarkAshraf96** [comment]
@ds-jhartmann @ds-jkreutzfeld Would you please check this?

**Comment by ds-jkreutzfeld** [comment]
Hi @MarkAshraf96, 
I'm not sure about the subcharts folder - IIRC, this was used in relation to being able to spin up the different images one by one, as done in the install shell scripts to reduce resource consumption on startup.

Regarding the custom charts:
At the time that deployment was created, not all charts were available to us or really usable for this case. The custom DAPS chart for example (omejdn-service) was used to easily provide the right configuration on startup automatically. The custom EDC charts were included because there was no proper out-of-the-box setup available then.

So if possible, we can always switch to stock charts, if it fits the use case. :)

**Comment by MarkAshraf96** [comment]
Thank You Jan for the feedback,
I see that currently that the charts for the  semantic-hub, discovery and keycloack are available.
I don't know what you mean by out-of-the-box setup for the EDC?

I tried to include the charts from the charts repository but I face a lot of dependency issues, and stuck on proceeding.

**Comment by MarkAshraf96** [comment]
If you cold also provide me with the baselines/releases used for the previously mentioned chart, that would be helpful.

**Comment by ds-jhartmann** [comment]
Hi @MarkAshraf96, sorry about the silence. Is this issues still relevant?
