### ISSUE TITLE
AAS 3.0.0 is implemented in IRS API Swagger docu

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#209]
**As** PO
**I want** api updated to currrent aas version 3.0.0,
**so that** that the API reflects always the current state.

## Hints / Details

- ...

## Outcome / Acceptance Criteria
* Swagger documentation examples were updated. In consultation with @ds-jhartmann we decided to compare with the data from DEV because the examples in the above-mentioned docs are incomplete. There are some attributes that we do not have on the IRS side but as we don't need them we decided not to add them (would have involved adding quite a few new classes under irs-models\src\main\java\org\eclipse\tractusx\irs\component\assetadministrationshell which is beyond the scope of the acceptance criteria, escpecially as we don't need these new attributes...).

### Outcome
- ...
### Acceptance Criteria
- [ ] IRS API Swagger docu is aligned with aas 3.0.0 (Responses and Samples)

## Out of Scope

- ...

**Comment by dsmf** [comment]
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/87c51d73f04445ea67c38148305e5eb41f644576/docs/README.md

**Comment by dsmf** [comment]
Outcome: Swagger documentation examples were updated. In consultation with @ds-jhartmann we decided to compare with the data from DEV because the examples in the above mentioned docs are incomplete. There are some attributes that we do not have on the IRS side but as we don't need them we decided not to add them (would have involved adding quite a few new classes under irs-models\src\main\java\org\eclipse\tractusx\irs\component\assetadministrationshell which is beyond the scope of the acceptance criteria, escpecially as we don't need these new attributes...).

**Comment by mkanal** [comment]
Hello @dsmf  and @ds-jhartmann 
I have checked https://irs.int.demo.catena-x.net/api/swagger-ui/index.html?configUrl=/api/api-docs/swagger-config#/Item%20Relationship%20Service/getJobForJobId and it differs from the one here https://raw.githubusercontent.com/eclipse-tractusx/sldt-digital-twin-registry/87c51d73f04445ea67c38148305e5eb41f644576/docs/README.md

**Comment by mkanal** [comment]
@dsmf  please create a new pbis story. Link this story to this one. Add label PO Review and assign story to @jzbmw.

1. JobResponse provides complete aas (as we receive from dDTR) in shell array
