### ISSUE TITLE
Script or Insomnia Collection is used to showcase the recursive traversal over a single part via the input of a key (single tuple of globalAssetId/bpnl pairs).

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#284]

**Comment by jzbmw** [comment]
original title: Script or Insomnia Collection is used to showcase the recursive traversal over a single part via the input of a key (single tuple of globalAssetId/bpnl pairs).

**Comment by ds-jhartmann** [comment]
@jzbmw I believe this issue was created by accident by clicking on the "convert to issue" icon next to an acceptance criteria in https://github.com/eclipse-tractusx/item-relationship-service/issues/243. Which is why I closed this last month. 
I see you changed the title and updated the description but it is still closed. Do we want to repone it?
