### ISSUE TITLE
Test CVE's for QG (Short Notice)

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/item-relationship-service#419]
FIX: 
- https://github.com/catenax-ng/tx-item-relationship-service/security/code-scanning/706 (706)
- https://github.com/catenax-ng/tx-item-relationship-service/security/code-scanning/663
- https://github.com/catenax-ng/tx-item-relationship-service/security/code-scanning/708 (708)

**Comment by mkanal** [comment]
@ds-ext-kmassalski  Please inform DevSecOps Team to be aware that this is located in eclipse-temurin image and we do not have any troubles regarding this in QG. Thank. In addition please take this to the DevSecOps hour. 

fyi 
@jzbmw @ds-jhartmann @ds-ext-sceronik @almadigabor

**Comment by SebastianBezold** [comment]
Hi @ds-ext-kmassalski and @mkanal,

We can definitely talk about it in the office hour again. Just to leave it here as well. @ds-ext-kmassalski is right with what he got from our TRG 4.02. We do indeed use base images as is, without any change. 
The base images we aligned on are [official ones on DockerHub](https://docs.docker.com/trusted-content/official-images/).
DockerHub is doing container scans for them and is publishing the results in [docker-library/repo-info](https://github.com/docker-library/repo-info). For our annotations in the "Notice for Docker images", we rely on that info being present. Altering the base image will render these scan results obsolete and our info in the notice wouldn't be correct anymore. 

Up until now, there is no process on updating previously released images, in case a vulnerability is fixed in the base image. So if you have any suggestion on such a process, that is overwriting image tags, feel free to suggest it in the office hours or the mailing list

**Comment by mkanal** [comment]
Finds were fixed and migration documented - aligned with devSecOps Team
