### ISSUE TITLE
Improve Configuration of Default Policy HELM configuration

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#542]
**As** Team
**I want** a comprehensible standard definition of a policy that is built correctly
**so that** use a policy that complies with the regulations and is compliant.

## Hints / Details
- ...

## Acceptance Criteria
- [x] Default Policy should be configured in the standard policy ordl schema in the HELM configuration  
- [x] Only one Default Policy could be configured in the yaml HELM configuration 
- [x] Adaption of policy store api according to change 
- [x] Using ORDL Schema of policy in yaml Values.yaml 
- [x] Update arc42 and admin documentation 
## Out of Scope

- ...

**Comment by dsmf** [comment]
## PR
https://github.com/eclipse-tractusx/item-relationship-service/pull/829

## Outcome
- [x] Default policy configuration now uses a JSON array of policies, with each element following the ODRL schema.
- [x] Initialization from the configured default policy has been adjusted accordingly. It takes the given definition now exactly as it is (e.g. validUntil of the default policy is no longer set programmatically but taken directly from the configuration).
- [x] The default policies can be entered as multiline text (JSON) in values.yaml file. 
- [x] In the application.yml file Base64 encoding is used because plain JSON caused problems in Spring. 
- [x] The helm template automatically converts the value from values.yaml to Base64. 
- [x] Documentation was updated
- [x] Tests were adjusted.  
- [ ] TODO Tested locally in helm

**Comment by dsmf** [comment]
@ds-kgassner, @mkanal  ready for test

**Comment by ds-kgassner** [comment]
- Tested via Insomnia successfully: Default policy configuration now uses a JSON array of policies, with each element following the ODRL schema.
- Tested via Insomnia successfully: Initialization from the configured default policy has been adjusted accordingly. It takes the given definition now exactly as it is (e.g. validUntil of the default policy is no longer set programmatically but taken directly from the configuration).
- Tested successfully: The default policies can be entered as multiline text (JSON) in values.yaml file.
- Tested via Insomnia successfully and checked files changes: In the application.yml file Base64 encoding is used because plain JSON caused problems in Spring. 
- Tested via Insomnia successfully and checked file changes: The helm template automatically converts the value from values.yaml to Base64.
- Checked file changes: Tests were adjusted.
- Administration guide updated

**Comment by mkanal** [comment]
IRS will only negotiate contracts for offers with a policy as defined in the Policy Store.
The following configuration value allows the definition of default policies to be used
if no policy has been defined via the Policy Store API.
If the policy check fails, a tombstone will be created and this node will not be processed.
Configure the default policies as JSON array using multiline string here.

LGFM PO acceptance in behalf of @jzbmw
