### ISSUE TITLE
Deploy product  on Association infrastructure (int.catena-x.net)

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#731]
**As** product
**I want** to deploy the product on new infrastructure
**so that** we are able to participate in release 24.8

## Link 
- relates to https://github.com/eclipse-tractusx/sig-infra/issues/515 
- relates to https://github.com/eclipse-tractusx/sig-infra/issues/516

## Hints / Details
- ArgocCD https://argocd.int.catena-x.net 
- Vault https://vault.int.catena-x.net 

## Acceptance Criteria
- [ ] Product is  deployed and running on association infrastructure 
- [ ] Rename branch catenax-environments to helm-environments 

## Out of Scope

- ...

**Comment by ds-jhartmann** [comment]
IRS is deployed and reachable via this URL https://irs.int.catena-x.net/api/swagger-ui/index.html
It is not yet functional, since the shared services URLs are not available yet, but this is not part of the ACs
New Helm Environments branch for association config: https://github.com/eclipse-tractusx/item-relationship-service/tree/helm-environments

**Comment by mkanal** [comment]
LGFM: PO acceptance in behalf of @jzbmw .
