### ISSUE TITLE
Access and Usage Policy Validation flow correction

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#757]
**As a** company
**I want** policy validation of supplier/customer CatalogItem against defines policy for BPNL or if not present against the default policy
**so that** no policies are used for validation that are assigned to other companies (BPNL) 

## Hints / Details

- ...

## Acceptance Criteria
- [x] GIVEN Policy Checker validates Policy before initiating Contract Negotiation WHEN no policy is defined for Supplier or Customer BPNL THEN only default Policy is used for validation 
- [x] Validation against all stored policies in Policy Store in case there is no policy defined for suppliert/customer BPNL is deactivated

## Out of Scope

- ...

**Comment by mkanal** [comment]
@ds-jhartmann please evaluate and check story in order to be prepared for next week's planning. Thank you very much.

**Comment by ds-jhartmann** [comment]
See org.eclipse.tractusx.irs.policystore.services.PolicyStoreService#getAcceptedPolicies https://github.com/eclipse-tractusx/item-relationship-service/blob/cc5ca9badb15d5731c4b60fda882c434e23d2650/irs-policy-store/src/main/java/org/eclipse/tractusx/irs/policystore/services/PolicyStoreService.java#L267-L273
here, all policies are returned, if the bpn is null. This should never be the case, so a `@NonNull` annotation for the BPN parameter instead of the null check should do the trick.

Estimation size: 1

**Comment by dsmf** [comment]
## PR
https://github.com/eclipse-tractusx/item-relationship-service/pull/788

**Comment by ds-kgassner** [comment]
approved from my side

**Comment by mkanal** [comment]
![image](https://github.com/user-attachments/assets/adaef5c1-bc8f-40d7-9ff4-72e34b3d6dda)

Current implementation uses the policy from the configuration (values.yaml). 
What is expected is that the current "Default Policy" from policy store MUST  be used instead.

**Comment by dsmf** [comment]
@mkanal: You are right. Configured default policies should only be the last fall back when there are no default policies in the DB.

**Comment by dsmf** [comment]
## PR for fix "fallback to default policies correctly":
https://github.com/eclipse-tractusx/item-relationship-service/pull/842

**Comment by mkanal** [comment]
LGFM. Works as intended. PO Acceptance in behalf of @jzbmw
