### ISSUE TITLE
[KITs] Remove API Plug-In in KITs

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/item-relationship-service#846]
## Hints / Details

- IRS API Hub URL would be https://eclipse-tractusx.github.io/api-hub/item-relationship-service/5.4.0/swagger-ui/

## Acceptance Criteria
- [ ] https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/972 is fixed

**Comment by dsmf** [comment]
## Outcome
- plugin was already removed in newer versions
- but still included in 24.03
- 24.03
  - removed the relevant *.api.mdx files from 24.03
  - linked to the Open API yaml file (because this version was not published on API-Hub)
- 24.05
  -  linked to the Open API yaml file (because this version was not published on API-Hub)
- next
  - linked to OpenAPI documentation on API-Hub

### PR
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/1002

**Comment by ds-kgassner** [comment]
Successfully tested - open API link exists and works:
- https://eclipse-tractusx.github.io/docs-kits/24.03/kits/Data%20Chain%20Kit/Software%20Development%20View/Job%20Api/irs-api/
- https://raw.githubusercontent.com/eclipse-tractusx/item-relationship-service/5.1.3/docs/src/api/irs-api.yaml
- https://eclipse-tractusx.github.io/api-hub/item-relationship-service/5.4.0/swagger-ui/

**Comment by dsmf** [comment]
@mkanal ready for PO-review
